// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

// +kubebuilder:object:generate=true
// +groupName=controlplane.cluster.x-k8s.io
package v1beta1

import clusterv1 "sigs.k8s.io/cluster-api/api/core/v1beta1"

// Deprecated v1beta1 contract conditions and condition Reasons for the TalosControlPlane object
// To be deleted when CAPI support for v1beta1 contract is removed

const (
	// MachinesReadyCondition reports an aggregate of current status of the machines controlled by the TalosControlPlane.
	MachinesReadyV1Beta1Condition clusterv1.ConditionType = "MachinesReady"
)

const (
	// MachinesBootstrapped is tracking control planes bootstrap status.
	MachinesBootstrappedV1Beta1Condition clusterv1.ConditionType = "MachinesBootstrapped"

	// WaitingForMachinesReason (Severity=Info) documents a TalosControlPlane bootstrap is waiting
	// for all control plane nodes to be created.
	WaitingForMachinesV1Beta1Reason = "WaitingForMachines"
)

const (
	// AvailableCondition documents that the first control plane instance has completed Talos boot sequence
	// and so the control plane is available and an API server instance is ready for processing requests.
	AvailableV1Beta1Condition clusterv1.ConditionType = "Available"

	// WaitingForTalosBootReason (Severity=Info) documents a TalosControlPlane object waiting for the first
	// control plane instance to complete Talos boot sequence.
	WaitingForTalosV1Beta1BootReason = "WaitingForTalosBoot"

	// InvalidControlPlaneConfigReason (Severity=Error) documents that controlplane config is invalid and the provider
	// can not proceed with the bootstrap.
	InvalidControlPlaneConfigV1Beta1Reason = "InvalidControlPlaneConfig"
)

const (
	// MachinesSpecUpToDateCondition documents that the spec of the machines controlled by the TalosControlPlane
	// is up to date. When this condition is false, the TalosControlPlane is executing a rolling upgrade.
	MachinesSpecUpToDateV1Beta1Condition clusterv1.ConditionType = "MachinesSpecUpToDate"

	// RollingUpdateInProgressReason (Severity=Warning) documents a TalosControlPlane object executing a
	// rolling upgrade for aligning the machines spec to the desired state.
	RollingUpdateInProgressV1Beta1Reason = "RollingUpdateInProgress"
)

const (
	// ResizedCondition documents a TalosControlPlane that is resizing the set of controlled machines.
	ResizedV1Beta1Condition clusterv1.ConditionType = "Resized"

	// ScalingUpReason (Severity=Info) documents a TalosControlPlane that is increasing the number of replicas.
	ScalingUpV1Beta1Reason = "ScalingUp"

	// ScalingDownReason (Severity=Info) documents a TalosControlPlane that is decreasing the number of replicas.
	ScalingDownV1Beta1Reason = "ScalingDown"
)

const (
	// ControlPlaneComponentsHealthyCondition reports the overall status of control plane components
	// implemented as static pods generated by Talos including kube-api-server, kube-controller manager,
	// kube-scheduler and etcd.
	ControlPlaneComponentsHealthyV1Beta1Condition clusterv1.ConditionType = "ControlPlaneComponentsHealthy"

	// ControlPlaneComponentsUnhealthyReason (Severity=Error) documents a control plane component not healthy.
	ControlPlaneComponentsUnhealthyV1Beta1Reason = "ControlPlaneComponentsUnhealthy"

	// ControlPlaneComponentsInspectionFailedReason documents a failure in inspecting the control plane component status.
	ControlPlaneComponentsInspectionFailedV1Beta1Reason = "ControlPlaneComponentsInspectionFailed"
)

const (
	// EtcdClusterHealthyCondition documents the overall etcd cluster's health.
	EtcdClusterHealthyV1Beta1Condition clusterv1.ConditionType = "EtcdClusterHealthyCondition"

	// EtcdClusterUnhealthyReason (Severity=Error) is set when the etcd cluster is unhealthy.
	EtcdClusterUnhealthyV1Beta1Reason = "EtcdClusterUnhealthy"
)

const (
	// MachinesCreatedCondition documents that the machines controlled by the TalosControlPlane are created.
	// When this condition is false, it indicates that there was an error when cloning the infrastructure/bootstrap template or
	// when generating the machine object.
	MachinesCreatedV1Beta1Condition clusterv1.ConditionType = "MachinesCreated"

	// InfrastructureTemplateCloningFailedReason (Severity=Error) documents a TalosControlPlane failing to
	// clone the infrastructure template.
	InfrastructureTemplateCloningFailedV1Beta1Reason = "InfrastructureTemplateCloningFailed"

	// BootstrapTemplateCloningFailedReason (Severity=Error) documents a TalosControlPlane failing to
	// clone the bootstrap template.
	BootstrapTemplateCloningFailedV1Beta1Reason = "BootstrapTemplateCloningFailed"

	// MachineGenerationFailedReason (Severity=Error) documents a TalosControlPlane failing to
	// generate a machine object.
	MachineGenerationFailedV1Beta1Reason = "MachineGenerationFailed"
)
